SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOOT_SPEED = 500

SHOT_RADIUS = 5

PLAYER_SHOOT_COOLDOWN = 0.3

EXPLOSION_DURATION = 0.5
EXPLOSION_MAX_PARTICLES = 15
EXPLOSION_SPEED_SCALE = 150

EXPLOSION_PARTICLE_MAX_RADIUS = SHOT_RADIUS
EXPLOSION_PARTICLE_MEDIUM_RADIUS = SHOT_RADIUS / 2
EXPLOSION_PARTICLE_MIN_RADIUS = SHOT_RADIUS / 4
